wandb:
  entity: dmitriykornilov_team
  project: DRIM
  
general:
  seed: 1999
  val_split: 4
  modalities: WSI
  n_outs: 20
  dropout: 0.2
  epochs: 50
  save_path: ./models/
  dim: 128
  n_folds: 5

dataloader:
  batch_size: 24
  pin_memory: true
  num_workers: 8
  persistent_workers: true

optimizer:
  name: AdamW
  params:
    lr: 1e-3
    weight_decay: 1e-2

scheduler:
  T_max: ${general.epochs}
  eta_min: 5e-6

data:
  dataset_path: 'outputs/embeddings_wsi/updated_dataframe_with_emb.csv' #data/files/rna_dna_mri_dataset.csv 
  base_path:
    mri: '/mnt/data/d.kornilov/BraTS_2023/MRI'
    rna: '/mnt/data/m.zubrikhina/TCGA/GBMLGG/RNA'
    dna: '/mnt/data/m.zubrikhina/TCGA/GBMLGG/DNAm'
    wsi: null